### ISSUE TITLE
Invalid zone mode 'error'

### ISSUE THREAD

**Issue by JP-Ellis** [Swamp-Ig/pizone#22]
I have a newly set up iZone system, and after integrating with Home Assistant, I noticed there was an issue with a mode apparently missing from some enum: `'error'`.

See for example this traceback:

```
2024-10-02 15:25:16.268 ERROR (MainThread) [homeassistant.helpers.dispatcher] Exception in zone_update when dispatching 'izone_zone_update': (<pizone.controller.Controller object at 0x721efb50dd90>, <pizone.zone.Zone object at 0x721ef3386f30>)
Traceback (most recent call last):
  File "/var/lib/private/hass/.venv/lib/python3.12/site-packages/homeassistant/components/izone/climate.py", line 502, in zone_update
    self.async_write_ha_state()
  File "/var/lib/private/hass/.venv/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/var/lib/private/hass/.venv/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/var/lib/private/hass/.venv/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1063, in __async_calculate_state
    capability_attr = self.capability_attributes
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/private/hass/.venv/lib/python3.12/site-packages/homeassistant/components/climate/__init__.py", line 323, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/private/hass/.venv/lib/python3.12/site-packages/homeassistant/components/climate/__init__.py", line 488, in capability_attributes
    supported_features = self.supported_features
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/private/hass/.venv/lib/python3.12/site-packages/homeassistant/components/climate/__init__.py", line 327, in __getattribute__
    _supported_features: ClimateEntityFeature = super().__getattribute__(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/private/hass/.venv/lib/python3.12/site-packages/homeassistant/components/izone/climate.py", line 126, in wrapped_f
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/private/hass/.venv/lib/python3.12/site-packages/homeassistant/components/izone/climate.py", line 517, in supported_features
    if self._zone.mode == Zone.Mode.AUTO:
       ^^^^^^^^^^^^^^^
  File "/var/lib/private/hass/.venv/lib/python3.12/site-packages/pizone/zone.py", line 71, in mode
    return self.Mode(self._get_zone_state("Mode"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'error' is not a valid Zone.Mode
```

The 'obvious' fix here is the add the undocumented `error` mode to the enum:

https://github.com/Swamp-Ig/pizone/blob/ef2eeb2ae22dd4435c0c5bb4e1fe365d45af8c1a/pizone/zone.py#L26-L35

There's no mention of this mode in the PDF docs, so I can understand not adding it; though having a runtime error is also less than ideal.

I'm not familiar with the codebase, so I'm not sure what potential ramifications there might be to adding this enum.

**Comment by Swamp-Ig** [comment]
Feel free to create a PR. I haven't really been developing the integration recently, I need someone else to get approved to review PRs really. Let me know if you'd be able to do this and would be interested.

**Comment by JP-Ellis** [comment]
If you aren't developing it much lately, I'm more than happy to contribute to it. What would be best? Would it be easier for me to simply fork your repository? Or do you want me to contribute into this repo?

**Comment by paulojr** [comment]
Hi JP-Ellis are you able to provide more info on how you encountered the "error" value in the field.  What izone unit and firmware would be useful and also the data that is posted back when you hit the CB_IP/SystemSettings and CB_IP/Zones1_4, CB_IP/Zones5_8 and CB_IP/Zones9_12 for zones (remove any personal data such as your system ID)
BTW I am happy to help test, but don't recall ever seeing this particular code returned so not sure how to reproduce that, perhaps it only occurs on a mis-configured system or something in a newer firmware.  Also may be wort raising a izone case to clarify why the documentation does not mention it.

**Comment by Swamp-Ig** [comment]
Probably the best bet if you want to actively contribute to development is to contact me on the home assistant discord, my username is `@Penny`

**Comment by JP-Ellis** [comment]
Well, somehow this fell of my radar 😅 

> Hi JP-Ellis are you able to provide more info on how you encountered the "error" value in the field. 

This was during the installation of the system. The installer was still there are configuring things. So most definitely this was a transient issue and I haven't seen it since.

> What izone unit and firmware would be useful and also the data that is posted back when you hit the CB_IP/SystemSettings and CB_IP/Zones1_4, CB_IP/Zones5_8 and CB_IP/Zones9_12 for zones (remove any personal data such as your system ID)

I'm unsure how to get them unfortunately. Trying to list the controllers with:

```python
import pizone
disco = pizone.discovery()
await disco.start_discovery()
disco.controllers
```

only returns an empty dictionary (this is despite the iZone controller being accessible in home assistant).

**Comment by Swamp-Ig** [comment]
Hey, I think this is now fixed in the latest pizone, now merged into home assistant. It's going to be hard to replicate - it's transient only. It seems to happen when the bridge is powered up before the aircon system is powered, or possibly if the breaker trips to the aircon and the bridge is up for some time.

It's a pretty odd set of circumstances, but it should now be handled gracefully.
