### ISSUE TITLE
Controller and Zone status don't update when notification is received

### ISSUE THREAD

**Issue by Maccas1313** [Swamp-Ig/pizone#4]
Hi Penny,

I hoping you can assist me, I am quite new with Home Assistant so apologies for my stupidity and if I am missing something. 

Everything appears to be interacting really well with my iZone controller but the controller and zones don't seem to proactively update their own state attributes when a new notification is received from the listener in pizone.discovery.

I am currently running HA in their Docker container (homeassistant/home-assistant:latest\dev). I have tried a few automations and scripts to force an update of information but with no luck.

I have attached some logs below, the logs start from after i have restarted HA. The initial discovery appears to update the attributes from the first discovery and there seems to be some errors from pre-existing entities. I don't imagine these errors would be the issue though.

Further down the log there is a constant stream of 'iZoneChanged_*' notifications from the controller but if (for example) the current temperature were to change this won't be reflected in the state attributes or the thermostat card on the lovelace page.

Even further down the log as a demonstration I have sent a command to a zone. Doing this results in the attributes successfully updating as well.

If there is anything i can do, please let me know.

Thank you,
Lachy

```
2020-02-26 16:52:49 INFO (MainThread) [pizone.discovery] Starting discovery protocol
2020-02-26 16:52:49 DEBUG (MainThread) [pizone.discovery] Sending discovery message to addr 192.168.X.X
2020-02-26 16:52:49 DEBUG (MainThread) [pizone.discovery] Sending discovery message to addr 192.168.X.X
2020-02-26 16:52:49 DEBUG (MainThread) [pizone.discovery] Sending discovery message to addr 172.17.0.1
2020-02-26 16:52:50 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'ASPort_12107,Mac_200001526,IP_192.168.X.X,iZone,iLight,iDrate'
2020-02-26 16:52:50 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'ASPort_12107,Mac_200001526,IP_192.168.X.X,iZone,iLight,iDrate'
2020-02-26 16:52:51 INFO (MainThread) [pizone.discovery] New controller found: id=200001526 ip=192.168.X.X
2020-02-26 16:52:51 INFO (MainThread) [homeassistant.components.izone.climate] Controller UID=200001526 discovered
2020-02-26 16:52:52 INFO (MainThread) [pizone.discovery] New controller found: id=200001526 ip=192.168.X.X
2020-02-26 16:52:52 INFO (MainThread) [homeassistant.components.izone.climate] Controller UID=200001526 discovered
2020-02-26 16:52:52 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 415, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: climate.izone_controller_200001526. Platform izone does not generate unique IDs
2020-02-26 16:52:52 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 415, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: climate.living. Platform izone does not generate unique IDs
2020-02-26 16:52:52 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 415, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: climate.family_kitch. Platform izone does not generate unique IDs
2020-02-26 16:52:52 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 415, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: climate.bath_bed_3. Platform izone does not generate unique IDs
2020-02-26 16:52:52 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 415, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: climate.study. Platform izone does not generate unique IDs
2020-02-26 16:52:52 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 415, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: climate.master. Platform izone does not generate unique IDs
2020-02-26 16:52:52 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 415, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: climate.bed_2. Platform izone does not generate unique IDs
2020-02-26 16:53:45 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-26 16:53:45 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-26 16:53:45 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Zones'
2020-02-26 16:53:45 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Zones'
2020-02-26 16:53:46 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Schedules'
2020-02-26 16:53:46 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Schedules'
2020-02-26 16:54:47 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-26 16:54:47 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-26 16:54:48 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Zones'
2020-02-26 16:54:48 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Zones'
2020-02-26 16:54:48 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Schedules'
2020-02-26 16:54:48 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Schedules'
2020-02-26 16:55:46 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-26 16:55:46 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-26 16:55:47 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Zones'
2020-02-26 16:55:47 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Zones'
2020-02-26 16:55:47 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Schedules'
2020-02-26 16:55:47 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Schedules'
2020-02-26 16:56:14 DEBUG (MainThread) [pizone.controller] Writing message to 192.168.X.X{"ZoneCommand": {"ZoneNo": "1", "Command": "23.5"}}
2020-02-26 16:56:15 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-26 16:56:15 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-26 16:57:17 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-26 16:57:17 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-26 16:57:18 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Zones'
2020-02-26 16:57:18 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Zones'
2020-02-26 16:57:18 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Schedules'
2020-02-26 16:57:18 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Schedules'
2020-02-26 16:57:49 DEBUG (MainThread) [pizone.discovery] Sending discovery message to addr 192.168.X.X
2020-02-26 16:57:49 DEBUG (MainThread) [pizone.discovery] Sending discovery message to addr 192.168.X.X
2020-02-26 16:57:49 DEBUG (MainThread) [pizone.discovery] Sending discovery message to addr 172.17.0.1
2020-02-26 16:57:49 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'ASPort_12107,Mac_200001526,IP_192.168.X.X,iZone,iLight,iDrate'
2020-02-26 16:57:49 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'ASPort_12107,Mac_200001526,IP_192.168.X.X,iZone,iLight,iDrate'
2020-02-26 16:58:20 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-26 16:58:20 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-26 16:58:20 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Zones'
2020-02-26 16:58:20 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Zones'
2020-02-26 16:58:21 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Schedules'
2020-02-26 16:58:21 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Schedules'```

**Comment by Swamp-Ig** [comment]
I think someone else had this same issue. From memory when they removed the integration, rebooted,  HA, and then re-added it then it worked again.

**Comment by Maccas1313** [comment]
Hey, thanks for getting back to me so quickly.

I have tried removing the integration and then rebooting with no luck unfortunately. I have also started a whole new docker container and tried different versions (0.100.3/ latest (0.105/0.106)/ dev 0.107) with no luck.

It seems when pizone.controller sends a zone command everything updates but with pizone.discovery, even though the loop is receiving notifications nothing happens.

I had spotted the issue https://github.com/home-assistant/home-assistant/issues/27395 previously but I can't figure out if the "Entity id already exists" error is connected to why the device states don't update.

**Comment by Swamp-Ig** [comment]
Hi,

When you remove the izone integration, try going into the entity registry screen and removing any izone entities. Then reboot and add the integration back again.

**Comment by Maccas1313** [comment]
No luck sorry, both the entity and device registries have no iZone references after removing the integration.

Re-added the integration but the controller and zone information still doesn't proactively poll\update.

Although, today i have noticed within a brand new container (homeassistant\home-assistant) and brand new instance of HA, when I add the iZone integration i instantly get the "Entity id already exists" errors.

```
2020-02-27 18:09:03 INFO (MainThread) [pizone.discovery] Starting discovery protocol
2020-02-27 18:09:03 DEBUG (MainThread) [pizone.discovery] Sending discovery message to addr 192.168.X.X
2020-02-27 18:09:03 DEBUG (MainThread) [pizone.discovery] Sending discovery message to addr 192.168.X.X
2020-02-27 18:09:03 DEBUG (MainThread) [pizone.discovery] Sending discovery message to addr 172.17.0.1
2020-02-27 18:09:03 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'ASPort_12107,Mac_200001526,IP_192.168.X.X,iZone,iLight,iDrate'
2020-02-27 18:09:03 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'ASPort_12107,Mac_200001526,IP_192.168.X.X,iZone,iLight,iDrate'
2020-02-27 18:09:03 INFO (MainThread) [pizone.discovery] New controller found: id=200001526 ip=192.168.X.X
2020-02-27 18:09:03 DEBUG (MainThread) [homeassistant.components.izone.config_flow] Controllers {'200001526': <pizone.controller.Controller object at 0x7f125e836810>}
2020-02-27 18:09:03 INFO (MainThread) [homeassistant.components.izone.climate] Controller UID=200001526 discovered
2020-02-27 18:09:03 INFO (MainThread) [pizone.discovery] New controller found: id=200001526 ip=192.168.X.X
2020-02-27 18:09:03 INFO (MainThread) [homeassistant.components.izone.climate] Controller UID=200001526 discovered
2020-02-27 18:09:03 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 425, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: climate.izone_controller_200001526. Platform izone does not generate unique IDs
2020-02-27 18:09:04 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 425, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: climate.study. Platform izone does not generate unique IDs
2020-02-27 18:09:04 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 425, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: climate.living. Platform izone does not generate unique IDs
2020-02-27 18:09:04 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 425, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: climate.master. Platform izone does not generate unique IDs
2020-02-27 18:09:04 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 425, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: climate.bath_bed_3. Platform izone does not generate unique IDs
2020-02-27 18:09:04 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 425, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: climate.family_kitch. Platform izone does not generate unique IDs
2020-02-27 18:09:04 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 425, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: climate.bed_2. Platform izone does not generate unique IDs
2020-02-27 18:09:04 DEBUG (MainThread) [pizone.controller] Writing message to 192.168.X.X{"ZoneCommand": {"ZoneNo": "5", "Command": "24"}}
2020-02-27 18:09:04 DEBUG (MainThread) [pizone.controller] Writing message to 192.168.X.X{"ZoneCommand": {"ZoneNo": "4", "Command": "24"}}
2020-02-27 18:09:04 DEBUG (MainThread) [pizone.controller] Writing message to 192.168.X.X{"ZoneCommand": {"ZoneNo": "6", "Command": "24"}}
2020-02-27 18:09:04 DEBUG (MainThread) [pizone.controller] Writing message to 192.168.X.X{"ZoneCommand": {"ZoneNo": "1", "Command": "23.5"}}
2020-02-27 18:09:04 DEBUG (MainThread) [pizone.controller] Writing message to 192.168.X.X{"ZoneCommand": {"ZoneNo": "2", "Command": "23.5"}}
2020-02-27 18:09:04 DEBUG (MainThread) [pizone.controller] Writing message to 192.168.X.X{"ZoneCommand": {"ZoneNo": "3", "Command": "close"}}
2020-02-27 18:09:04 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-27 18:09:04 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-27 18:09:04 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Zones'
2020-02-27 18:09:04 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Zones'
2020-02-27 18:09:05 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Schedules'
2020-02-27 18:09:05 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Schedules'
2020-02-27 18:10:06 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-27 18:10:06 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-27 18:10:07 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Zones'
2020-02-27 18:10:07 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Zones'
2020-02-27 18:10:07 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Schedules'
2020-02-27 18:10:07 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Schedules'
2020-02-27 18:11:09 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-27 18:11:09 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_System'
2020-02-27 18:11:09 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Zones'
2020-02-27 18:11:09 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Zones'
2020-02-27 18:11:10 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Schedules'
2020-02-27 18:11:10 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'iZoneChanged_Schedules'
```

**Comment by Maccas1313** [comment]
Hi again, apologies but i have been able to get things working. It seems that the Docker container suggested by the homeassistant website was the cause of the issues. I have moved to another container to go to Hass.io instead and everything has worked straight away.

Apologies again and thank you so much for your help! Really appreciate this component and all of the hard work you done to help all of us iZone users :)
